name: Build ICS
on:
  push:
    branches: [master]
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch: # allow manual runs

permissions:
  pages: write
  id-token: write

# Avoid overlapping deploys
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python main.py

      - run: mkdir _site && mv racedays.ics unconfirmed-racedays.ics _site/

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - id: deploy
        uses: actions/deploy-pages@v4
